language: csharp
solution: KTOP.sln
install:
  - nuget restore KTOP.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release KTOP.sln
